language: ruby

rvm:
  - 1.9.3

bundler_args: --without development

branches:
  only:
    - master
    - develop

before_install:
# remove this line after bundler 1.2.0 is out
  - "gem install bundler --pre"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

notifications:
  email:
    - rubeque@scimedsolutions.com
